#!/usr/bin/env bash
# Build the no_openat2 shim and emit a `tar` wrapper that preloads it.
#
# Prints the wrapper directory on stdout; the caller prepends it to PATH so
# bitbake's HOSTTOOLS symlink for `tar` resolves to the wrapper.
#
# Why: see scripts/hosttools/no_openat2.c — GNU tar >= 1.35 + pseudo breaks
# do_package on every recipe. Harmless on hosts with older tar.
set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${1:?usage: setup-hosttools-shim.sh <output-dir>}"
mkdir -p "$OUT_DIR"

SHIM_SO="$OUT_DIR/no_openat2.so"
SHIM_C="$SRC_DIR/no_openat2.c"

if [ ! -f "$SHIM_SO" ] || [ "$SHIM_C" -nt "$SHIM_SO" ]; then
    cc -shared -fPIC -O2 -o "$SHIM_SO" "$SHIM_C" -ldl
fi

# Resolve the real tar, ignoring any wrapper we previously installed.
REAL_TAR=""
_ifs="$IFS"; IFS=:
for d in $PATH; do
    [ "$d" = "$OUT_DIR" ] && continue
    if [ -x "$d/tar" ] && [ ! -d "$d/tar" ]; then REAL_TAR="$d/tar"; break; fi
done
IFS="$_ifs"
[ -n "$REAL_TAR" ] || REAL_TAR=/usr/bin/tar

cat > "$OUT_DIR/tar" <<EOF
#!/bin/sh
# Generated by scripts/hosttools/setup-hosttools-shim.sh — do not edit.
LD_PRELOAD="$SHIM_SO\${LD_PRELOAD:+:\$LD_PRELOAD}"
export LD_PRELOAD
exec "$REAL_TAR" "\$@"
EOF
chmod +x "$OUT_DIR/tar"

echo "$OUT_DIR"
